language: python
sudo: false
notifications:
  email: false

services:
  - postgresql

branches:
  only:
    - master

cache:
  pip: true
  directories:
    - node_modules

matrix:
  include:
    - python: "3.6-dev" # 3.6 development branch
      env: TO_RUN="coverage"
    - python: "3.6-dev" # 3.7 development branch
      env: TO_RUN="postgres-test"
    - python: "3.6-dev"
      env: TO_RUN="lint"
    - python: "3.7-dev"
      env: TO_RUN="mypy"
    - python: "3.7-dev"
      env: TO_RUN="yapf"
    - python: "3.7-dev" # 3.7 development branch
      env: TO_RUN="tests"
    - python: "nightly" # currently points to 3.8-dev
      env: TO_RUN="tests"

install:
  - pip install -U wheel
  - pip install coveralls pytest-cov
  - pip install codecov
  - pip install celery[redis]
  - pip install -r requirements.txt

before_script:
  - mkdir -p /tmp/psef/uploads
  - mkdir -p /tmp/psef/mirror_uploads
  - python --version
  - export PYTHONPATH="$PYTHONPATH:$(pwd)"
  - export DEBUG_ON=True
  - psql -c 'create database travis_ci_test;' -U postgres
  - pip install travis-sphinx

script:
  - bash ./.travis/run
  - "[[ $TO_RUN = 'coverage' ]] && travis-sphinx build --source=docs/ || true"

after_success:
  "[[ $TO_RUN = 'coverage' ]] && ( coveralls; codecov; travis-sphinx deploy -c docs.codegra.de; )"
