#!/bin/bash

changed_files() {
    git diff --name-only HEAD "$(git merge-base HEAD master)"
}

run_config_changed() {
    changed_files | grep '.*travis.*\|Makefile\|setup\.cfg'
}

should_run_py_tests() {
    run_config_changed || changed_files | grep '\.\(py\|json\)$\|requirements.txt'
}

should_run_js_tests() {
    run_config_changed || changed_files | grep '\.\(js\|vue\|json\|less\)$\|package.json'
}

res=0

echo "Running test with pwd: $(pwd)"

set -o xtrace

if [[ "$TO_RUN" = "postgres-test" ]]; then
    TEST_FLAGS="--postgresql=travis_ci_test"
    SQLALCHEMY_DATABASE_URI='postgresql:///travis_ci_test' ./manage.py db upgrade
fi

case "$TO_RUN" in
    "coverage")
        if should_run_py_tests; then
            make test
            res="$?"
            if [[ "$res" -eq 0 ]]; then
                make test TEST_FILE= TEST_FLAGS='--cov-append --doctest-modules psef'
                res="$?"
            fi
        fi
        ;;
    "tests"|"postgres-test")
        if should_run_py_tests; then
            make test TEST_FLAGS="$TEST_FLAGS"
            res="$?"
            if [[ "$res" -eq 0 ]]; then
                make -C docs html
                res="$?"
            fi
            if [[ "$res" -eq 0 ]]; then
                make test TEST_FILE= TEST_FLAGS='--doctest-modules psef'
                res="$?"
            fi
        fi
        ;;
    "mypy")
        if should_run_py_tests; then
            make mypy
            res="$?"
        fi
        ;;
    "lint")
        if should_run_py_tests; then
            make lint-py
            res="$?"
        fi
        if should_run_js_tests; then
            make lint-js
            [ "$res" == 0 ] && res="$?"
        fi
        ;;
    "yapf")
        if should_run_py_tests; then
            make format FORMAT_FLAGS="-rdp '$(pwd)/psef' '$(pwd)/psef_test'"
            res="$?"
        fi
        ;;
    *)
        res=127
        ;;
esac

set +o xtrace

exit "$res"
